### ISSUE TITLE
[BUG] i2pd.conf is always unconditionally overwritten

### ISSUE THREAD

**Issue by mtalexan** [diva-exchange/i2p#5]
The README.md says to mount over the `/home/i2pd/conf/` folder, but the `entrypoint.sh` is always unconditionally overwriting the `i2pd.conf` in this folder based on the `/home/i2pd/i2pd.org.conf` template file and then substituting the variables in it.

---

I think the intent was to make the `i2pd.conf` configurable, but it's not at all based on the `entrypoint.sh`.

**Comment by diva-exchange** [comment]
The intention of the docker image divax/i2p is to overwrite the configuration file (unconditionally). The configuration of a container is done using environment variables. Hence the README.md is misleading and should be fixed by removing the sentence regarding "mounting the configuration folder". Users looking for docker images supporting overloading i2pd config files could use this repo: https://github.com/PurpleI2P/i2pd . Overloading configuration files is a solution approach with a different security profile than using environment variables (as this docker image). This docker image is also oppinionated towards the use cases of diva.exchange, like here: https://github.com/diva-exchange/diva-dockerized

**Comment by mtalexan** [comment]
Makes sense, that was my guess, but I didn't want to presume. It's just a documentation issue then.
